config/routes.rb
Rails.application.routes.draw do

  root 'shelters#index'

  resources :phone_updater
  resources :shelters
  devise_for :users

end

app/models/shelter.rb
class Shelter < ActiveRecord::Base
  # attributes = name, description, address, phone
  validates :name, presence:true

  belongs_to :user
  
  # has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, default_url: "http://placehold.it/700x700&text=Whoops!+No+Image" 
  # has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, default_url: "http://placehold.it/300x300&text=Whoops!+No+Image"
  # validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  # validates :image, presence: true

end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController

  before_action :set_shelter, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :belongs_to_user, only: [:edit, :update, :destroy]
  before_action :owner, only: [:edit, :update, :destroy]
  before_action :admin, only: [:new]

  attr_accessor :gmap_address

  def index
    @shelters = Shelter.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shelters }
    end
  end

  def show
    gmap(@shelter.address)
  end

  def new
    @shelter = current_user.shelters.build
  end

  def create

    @shelter = current_user.shelters.build(shelter_params)
    if @shelter.save
      flash[:success] = "'#{@shelter.name}' was successfully created."
      redirect_to @shelter
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @shelter.update_attributes(shelter_params)
      flash[:success] = "'#{@shelter.name}' was successfully edited."
      redirect_to @shelter
    else
      render action: 'edit'
    end
  end

  def destroy
    @shelter.destroy
    redirect_to shelters_path, success: "'#{@shelter.name}' was successfully deleted."
  end

  def gmap(value)
    @gmap = 'https://maps.googleapis.com/maps/api/staticmap?markers='+value.gsub(' ', '+')+'&zoom=13&size=400x200&maptype=roadmap'
  end

  private

  # For any single shelther instance, set the default @shelter
  def set_shelter
    @shelter = Shelter.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def shelter_params
    params.require(:shelter).permit(:name, :description, :address, :phone, :gender, :free_bed)
  end

  # Allow modifications only for each shelter's owner, unless you're an admin
  def belongs_to_user
    unless current_user.admin
      @shelter = current_user.shelters.find_by(id: params[:id]) 
      redirect_to shelter_path, notice: 'Woah there! That shelter belongs to someone else.' if @shelter.nil?
    end
  end

  # Allow modifications only for owners or admins
  def owner
    redirect_to shelters_path, notice: 'Woah there! Only owners can edit shelters.' unless current_user.owner || current_user.admin
  end

  # Allow new shelter creation only for admins
  def admin
    redirect_to shelters_path, notice: 'Woah there! Only admins can create shelters.' unless current_user.admin
  end

end

app/helpers/shelter_helper.rb
module ShelterHelper

  def availability_popover_class(shelter)
    if shelter.free_bed.nil?
      "default"
    else
      if shelter.free_bed > 9
        "success"
      elsif shelter.free_bed < 5 && shelter.free_bed > 1
        "danger"
      elsif shelter.free_bed < 2
        "danger"
      else
        "warning"
      end
    end
  end

  def availability_popover_content(shelter)
    if shelter.free_bed.nil?
      "We don't have any information about current bed availability."
    else
      if shelter.free_bed == 1
        "There is #{shelter.free_bed} bed currently available."
      else
        "There are #{shelter.free_bed} beds currently available."
      end
    end
  end

  def availability_popover_title(shelter)
    if shelter.free_bed.nil?
      "Unknown Availability"
    else
      if shelter.free_bed > 10
        "High Availability"
      elsif shelter.free_bed < 5 && shelter.free_bed > 1
        "Low Availability"
      elsif shelter.free_bed < 2
        "One Bed Left"
      else
        "Medium Availability"
      end
    end
  end

  def free_beds(shelter)
    shelter.free_bed ? shelter.free_bed : "?"
  end

  def gmap(shelters)
    gmap_addresses = ''
    shelters.each do |shelter|
      gmap_addresses << 'markers='+shelter.address.gsub(' ', '+')+'&'
    end
    image_tag 'https://maps.googleapis.com/maps/api/staticmap?'+gmap_addresses+'size=800x400&maptype=roadmap'
  end

  def addresses(shelters)
    addresses = []
    shelters.each do |shelter|
      addresses << shelter.address
    end
    addresses
  end

  def names(shelters)
    names = []
    shelters.each do |shelter|
      names << shelter.name
    end
    names
  end

  def no_bed_info(shelter)
    shelter.free_bed.nil?
  end

  def shelter_name_id(name)
    name.downcase.gsub('\'','').gsub(' ','')
  end

  def shelters_info(shelters)
    all_info = []
    shelters.each do |shelter|
      info = []
      info << shelter.name
      info << shelter.description
      info << shelter.address
      info << shelter.phone
      all_info << info
    end
    all_info
  end

end

app/views/shelters/_form.html.erb
<%= form_for @shelter, :html => {:class => "form-horizontal"} do |f| %>

    <% @shelter.errors.full_messages.each do |error| %>
      <li><%= error %></li>
      <% end %>
    <div class="form-group">
      <label for="name" class="col-sm-2 control-label">Name</label>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name', type: 'text' %>
      </div>
    </div>
    <div class="form-group">
      <label for="name" class="col-sm-2 control-label">Description</label>
      <div class="col-sm-10">
        <%= f.text_field :description, class: 'form-control', placeholder: 'Description', type: 'text' %>
      </div>
    </div>
    <div class="form-group">
      <label for="name" class="col-sm-2 control-label">Address</label>
      <div class="col-sm-10">
        <%= f.text_field :address, class: 'form-control', placeholder: 'Address', type: 'text' %>
      </div>
    </div>
    <div class="form-group">
      <label for="name" class="col-sm-2 control-label">Phone</label>
      <div class="col-sm-10">
        <%= f.text_field :phone, class: 'form-control', placeholder: 'Phone', type: 'text' %>
      </div>
    </div>
    <div class="form-group">
      <label for="name" class="col-sm-2 control-label">Gender of Guests</label>
      <div class="col-sm-10">
        <%= f.select :gender, [['Women and Men', 'Women and Men'],['Women', "Women"], ['Men', "Men"]],class: 'form-control', placeholder: 'Gender', type: 'text' %>
      </div>
    </div>
    <div class="form-group">
      <label for="name" class="col-sm-2 control-label">Average Number of Free Beds*</label>
      <div class="col-sm-10">
          <%= f.number_field :free_bed, class: 'form-control', placeholder: 'Free Bed'%>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
        <% if user_signed_in? && (params[:action] == 'new') %>
          <%= link_to "Cancel", shelters_path, class: 'btn btn-default' %>
        <% else %>
          <%= link_to "Cancel", shelter_path(@shelter), class: 'btn btn-default'%>
        <% end %>
      </div>
    </div>

<% end %>

app/views/shelters/edit.html.erb
<h1 class="text-center">Edit '<%= @shelter.name %>' </h1>
<hr>
<%= render partial: 'form' %>

app/views/shelters/index.html.erb
<div>
  <h1><span class="hidden-xs">Shelters</span>

    <div class="visible-xs">
      <h1>Shelters</h1>
      <a class="btn btn-default toggle-view list">
        <span class="view-map">
          <i class="fa fa-map-o"></i>
          <span>View Map</span>
        </span>
        <span class="view-list">
          <i class="fa fa-list-ul"></i>
          <span>View List</span>
        </span>
      </a>
    </div>
    <div class="map-buttons">
      <a class="btn btn-default" onclick="showAll()" id="all_shelters">Zoom Out</a>
      <span class="loading"></span>
      <a class="btn btn-primary hide" onclick="showMarker()" id="closest_shelter">Find Closest</a>
    </div>
  </h1>
</div>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Gender</th>
    <th>Distance</th>
    <th>Map</th>
  </tr>
  <% @shelters.each do |shelter| %>
    <tr id="<%= shelter.id %>">
      <td><div>
        <a href="#" tabindex="0" class="label label-<%= availability_popover_class(shelter) %>" data-trigger="focus" data-toggle="popover" data-placement="top" title="<%= availability_popover_title(shelter) %>" data-content="<%= availability_popover_content(shelter) %>"><%= free_beds(shelter) %></a>
        <%= link_to shelter.name, shelter %>
        </div>
      </td>
      <td><div><%= shelter.address %></div></td>
      <td><div><%= shelter.phone %></div></td>
      <td><div><%= shelter.gender %></div></td>
      <td><div><span class="distance">Loading...</span></div></td>
      <td><div class="hidden-xs"><a class="view-on-map" onclick="showMarker(<%= shelter.id %>)" data-info="" data-marker="">View</a></div></td>
    </tr>
  <% end %>

</table>




<div id="map_wrapper">
    <a class="btn btn-default compass" onclick="showMe()" id="user_location">
      <img src="https://i.imgur.com/QoHMbd5.png" class="img-resposive">
    </a>
    <div id="map_canvas" class="mapping"></div>
</div>

<%= javascript_include_tag "shelters" %>

app/views/shelters/new.html.erb
<h1>New Shelter</h1>
<%= render partial: 'form' %>

app/views/shelters/show.html.erb
<h1>
  <%= @shelter.name %>

  <% if user_signed_in? && @shelter.user == current_user %>
    <%= link_to "Edit", edit_shelter_path(@shelter), class: 'btn btn-default' %>
    <%= link_to "Delete", shelter_path(@shelter), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-default' %>
  <% end %>
</h1>
<p><em><%= @shelter.description %></em></p>
<p><%= @shelter.address %> </p>
<p><%= @shelter.phone %> </p>
<p><%= @shelter.gender %> </p>
<p><%= @shelter.free_bed %> </p>
<p><%= gmap([@shelter]) %></p>

<p>
  <%= link_to "Back to Shelters", shelters_path, class: 'btn btn-primary' %>
  <% if user_signed_in? %>
    <% if current_user.admin || current_user.owner %>
      <%= link_to "Edit", edit_shelter_path, class: 'btn btn-default'%>
    <% end %>
  <% end %>
</p>