config/routes.rb
Rails.application.routes.draw do

  root 'shelters#index'

  resources :phone_updater
  resources :shelters
  devise_for :users

end

app/models/phone_updater.rb
class PhoneUpdater < ActiveRecord::Base
end

app/controllers/phone_updater_controller.rb
class PhoneUpdaterController < ApplicationController

    def index
        @shelters = Shelter.all
    end

    def show
        @shelter = Shelter.find(params[:id])
        #stuff goes here about 
        @phones = PhoneUpdater.all
    end

    def create
    end

    def delete
    end

    private

    def phone_params
       params.require(:phone_updaters).permit(:shelter_id, :phone_number)
    end
end

app/helpers/phone_updater_helper.rb
module PhoneUpdaterHelper
end

app/views/phone_updater/index.html.erb
<h1>

  Shelters
  

</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
  </tr>
  <% @shelters.each do |shelter| %>
    <tr id="<%= shelter.name.downcase.gsub('\'','').gsub(' ','') %>">
      <td><strong><%= link_to shelter.name, phone_updater_path(shelter.id) %></strong></td>
      <td><%= shelter.id %>

    </tr>
  <% end %>

</table>

app/views/phone_updater/show.html.erb
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Phone Numbers</th>
  </tr>
 
    <tr id="<%= @shelter.name.downcase.gsub('\'','').gsub(' ','') %>">
      <td><strong><%= link_to @shelter.name, phone_updater_path(@shelter.id) %></strong></td>
      <!-- This next line should break the page if phone_updater table is empty -->
      <% @phones.each do |x| %>
        <% if x.shelter_id==shelter.id %>
            <%= x.phone_number %><p>, <p>
        <% end %>


    </tr>
  <% end %>