config/routes.rb
Rails.application.routes.draw do

  root 'shelters#index'

  resources :phone_updater
  resources :shelters
  devise_for :users

end

app/views/layouts/_head.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width initial-scale=1" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<meta name="application-name" content="Youth Shelter Finder" />
<title>Youth Shelter Finder</title>
<meta name="description" content="A web app to help find the nearest shelter in Boston.">
<meta name="robots" content="index, follow">
<!--[if lt IE 9]>
  <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= javascript_include_tag :modernizr %>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<%= csrf_meta_tags %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Youth Shelter Finder", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%#= link_to "About", about_path %></li>
      <% if user_signed_in? %>
        <% if current_user.admin %>
          <li><%= link_to "Admin Account", edit_user_registration_path %></li>
          <li><%= link_to "New Shelter", new_shelter_path %></li>
        <% elsif current_user.owner %>
          <li><%= link_to "Owner Account", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "User Account", edit_user_registration_path %></li>
        <% end %>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Log In", user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/head' %>
</head>
<body class="<%= controller_name %> <%= action_name %>">

<%= render 'layouts/header' %>

<div class="container list">
  <% flash.each do |name, msg| %>
    <div class='alert alert-info text-center alert-dismissible' role="alert">
      <strong><%= name.capitalize %>:</strong> <span><%= msg %></span>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>